### ISSUE TITLE
rerun Paginationwithhashchange2()

### ISSUE THREAD

**Issue by ragefuljoe** [cpbaumann/jquery.pagination2-with-hash-change#1]
Is there some way to update the list, then rerun Paginationwithhashchange2()? When I do that nothing happens. No errors in console, but paging isn't run.

thanks

**Comment by cpbaumann** [comment]
hi ragefuljoe,

At the monent it is based on static html and the plugin is initialised (with the found items in the list) once. 
But i had to rewirte the plugin complete for responsive use. The plan is to enable a destroy and reinit feature, cause i want to restart  the plugin with other values. (like itemsPerPage)

This version here is not aware of a dynamic (scripted) update of the itemslist.
In the new version this can maybee happen via destroy and restart of the plugin on useraction.   

c.

**Comment by ragefuljoe** [comment]
ok thanks. will it be a new repo? I found a hackish way to get it working by manually calling $(.next).click() then $(.prev).click(). obv this might cause problems if there isn't a next.

**Comment by cpbaumann** [comment]
It will be a new repo!

**Comment by cpbaumann** [comment]
still beta! https://github.com/cpbaumann/jquery.responsive.pagination-with-hash-change
